# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: natsio_schema.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor  # type:ignore
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="natsio_schema.proto",
    package="com.pec.natsioschema",
    syntax="proto3",
    serialized_options=_b("\n\024com.pec.natsioschema"),
    serialized_pb=_b(
        '\n\x13natsio_schema.proto\x12\x14\x63om.pec.natsioschema"\x7f\n\x10MetricSubmission\x12\x31\n\tsite_info\x18\x01 \x01(\x0b\x32\x1e.com.pec.natsioschema.SiteInfo\x12\x38\n\rmetric_groups\x18\x02 \x03(\x0b\x32!.com.pec.natsioschema.MetricGroup"\x86\x01\n\x0bMetricGroup\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x35\n\x0b\x64\x65vice_info\x18\x02 \x01(\x0b\x32 .com.pec.natsioschema.DeviceInfo\x12-\n\x07metrics\x18\x03 \x03(\x0b\x32\x1c.com.pec.natsioschema.Metric"\xa6\x02\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x15\n\x0bint32_value\x18\x03 \x01(\x05H\x00\x12\x16\n\x0cuint32_value\x18\x04 \x01(\rH\x00\x12\x15\n\x0bint64_value\x18\x05 \x01(\x03H\x00\x12\x16\n\x0cuint64_value\x18\x06 \x01(\x04H\x00\x12\x15\n\x0b\x66loat_value\x18\x07 \x01(\x02H\x00\x12\x16\n\x0c\x65num16_value\x18\x08 \x01(\rH\x00\x12\x16\n\x0c\x65num32_value\x18\t \x01(\rH\x00\x12\x1a\n\x10\x62itfield16_value\x18\n \x01(\rH\x00\x12\x1a\n\x10\x62itfield32_value\x18\x0b \x01(\rH\x00\x12\x13\n\tstr_value\x18\x0c \x01(\tH\x00\x42\x0e\n\x0cmetric_value"s\n\nDeviceInfo\x12\r\n\x05model\x18\x01 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x02 \x01(\t\x12\x15\n\rserial_number\x18\x03 \x01(\t\x12\x16\n\x0e\x64river_version\x18\x04 \x01(\t\x12\x11\n\tdevice_id\x18\x05 \x01(\t",\n\x08SiteInfo\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\tB\x16\n\x14\x63om.pec.natsioschemab\x06proto3'
    ),
)


_METRICSUBMISSION = _descriptor.Descriptor(
    name="MetricSubmission",
    full_name="com.pec.natsioschema.MetricSubmission",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="site_info",
            full_name="com.pec.natsioschema.MetricSubmission.site_info",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="metric_groups",
            full_name="com.pec.natsioschema.MetricSubmission.metric_groups",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=45,
    serialized_end=172,
)


_METRICGROUP = _descriptor.Descriptor(
    name="MetricGroup",
    full_name="com.pec.natsioschema.MetricGroup",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="timestamp",
            full_name="com.pec.natsioschema.MetricGroup.timestamp",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="device_info",
            full_name="com.pec.natsioschema.MetricGroup.device_info",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="metrics",
            full_name="com.pec.natsioschema.MetricGroup.metrics",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=175,
    serialized_end=309,
)


_METRIC = _descriptor.Descriptor(
    name="Metric",
    full_name="com.pec.natsioschema.Metric",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="com.pec.natsioschema.Metric.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="unit",
            full_name="com.pec.natsioschema.Metric.unit",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="int32_value",
            full_name="com.pec.natsioschema.Metric.int32_value",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="uint32_value",
            full_name="com.pec.natsioschema.Metric.uint32_value",
            index=3,
            number=4,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="int64_value",
            full_name="com.pec.natsioschema.Metric.int64_value",
            index=4,
            number=5,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="uint64_value",
            full_name="com.pec.natsioschema.Metric.uint64_value",
            index=5,
            number=6,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="float_value",
            full_name="com.pec.natsioschema.Metric.float_value",
            index=6,
            number=7,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="enum16_value",
            full_name="com.pec.natsioschema.Metric.enum16_value",
            index=7,
            number=8,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="enum32_value",
            full_name="com.pec.natsioschema.Metric.enum32_value",
            index=8,
            number=9,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="bitfield16_value",
            full_name="com.pec.natsioschema.Metric.bitfield16_value",
            index=9,
            number=10,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="bitfield32_value",
            full_name="com.pec.natsioschema.Metric.bitfield32_value",
            index=10,
            number=11,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="str_value",
            full_name="com.pec.natsioschema.Metric.str_value",
            index=11,
            number=12,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="metric_value",
            full_name="com.pec.natsioschema.Metric.metric_value",
            index=0,
            containing_type=None,
            fields=[],
        ),
    ],
    serialized_start=312,
    serialized_end=606,
)


_DEVICEINFO = _descriptor.Descriptor(
    name="DeviceInfo",
    full_name="com.pec.natsioschema.DeviceInfo",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="model",
            full_name="com.pec.natsioschema.DeviceInfo.model",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="manufacturer",
            full_name="com.pec.natsioschema.DeviceInfo.manufacturer",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="serial_number",
            full_name="com.pec.natsioschema.DeviceInfo.serial_number",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="driver_version",
            full_name="com.pec.natsioschema.DeviceInfo.driver_version",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="device_id",
            full_name="com.pec.natsioschema.DeviceInfo.device_id",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=608,
    serialized_end=723,
)


_SITEINFO = _descriptor.Descriptor(
    name="SiteInfo",
    full_name="com.pec.natsioschema.SiteInfo",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="tenant",
            full_name="com.pec.natsioschema.SiteInfo.tenant",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="location",
            full_name="com.pec.natsioschema.SiteInfo.location",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=725,
    serialized_end=769,
)

_METRICSUBMISSION.fields_by_name["site_info"].message_type = _SITEINFO
_METRICSUBMISSION.fields_by_name["metric_groups"].message_type = _METRICGROUP
_METRICGROUP.fields_by_name["device_info"].message_type = _DEVICEINFO
_METRICGROUP.fields_by_name["metrics"].message_type = _METRIC
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["int32_value"]
)
_METRIC.fields_by_name["int32_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["uint32_value"]
)
_METRIC.fields_by_name["uint32_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["int64_value"]
)
_METRIC.fields_by_name["int64_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["uint64_value"]
)
_METRIC.fields_by_name["uint64_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["float_value"]
)
_METRIC.fields_by_name["float_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["enum16_value"]
)
_METRIC.fields_by_name["enum16_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["enum32_value"]
)
_METRIC.fields_by_name["enum32_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["bitfield16_value"]
)
_METRIC.fields_by_name["bitfield16_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["bitfield32_value"]
)
_METRIC.fields_by_name["bitfield32_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
_METRIC.oneofs_by_name["metric_value"].fields.append(
    _METRIC.fields_by_name["str_value"]
)
_METRIC.fields_by_name["str_value"].containing_oneof = _METRIC.oneofs_by_name[
    "metric_value"
]
DESCRIPTOR.message_types_by_name["MetricSubmission"] = _METRICSUBMISSION
DESCRIPTOR.message_types_by_name["MetricGroup"] = _METRICGROUP
DESCRIPTOR.message_types_by_name["Metric"] = _METRIC
DESCRIPTOR.message_types_by_name["DeviceInfo"] = _DEVICEINFO
DESCRIPTOR.message_types_by_name["SiteInfo"] = _SITEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetricSubmission = _reflection.GeneratedProtocolMessageType(
    "MetricSubmission",
    (_message.Message,),
    dict(
        DESCRIPTOR=_METRICSUBMISSION,
        __module__="natsio_schema_pb2"
        # @@protoc_insertion_point(class_scope:com.pec.natsioschema.MetricSubmission)
    ),
)
_sym_db.RegisterMessage(MetricSubmission)

MetricGroup = _reflection.GeneratedProtocolMessageType(
    "MetricGroup",
    (_message.Message,),
    dict(
        DESCRIPTOR=_METRICGROUP,
        __module__="natsio_schema_pb2"
        # @@protoc_insertion_point(class_scope:com.pec.natsioschema.MetricGroup)
    ),
)
_sym_db.RegisterMessage(MetricGroup)

Metric = _reflection.GeneratedProtocolMessageType(
    "Metric",
    (_message.Message,),
    dict(
        DESCRIPTOR=_METRIC,
        __module__="natsio_schema_pb2"
        # @@protoc_insertion_point(class_scope:com.pec.natsioschema.Metric)
    ),
)
_sym_db.RegisterMessage(Metric)

DeviceInfo = _reflection.GeneratedProtocolMessageType(
    "DeviceInfo",
    (_message.Message,),
    dict(
        DESCRIPTOR=_DEVICEINFO,
        __module__="natsio_schema_pb2"
        # @@protoc_insertion_point(class_scope:com.pec.natsioschema.DeviceInfo)
    ),
)
_sym_db.RegisterMessage(DeviceInfo)

SiteInfo = _reflection.GeneratedProtocolMessageType(
    "SiteInfo",
    (_message.Message,),
    dict(
        DESCRIPTOR=_SITEINFO,
        __module__="natsio_schema_pb2"
        # @@protoc_insertion_point(class_scope:com.pec.natsioschema.SiteInfo)
    ),
)
_sym_db.RegisterMessage(SiteInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
